from .config import (
    MIN_DELAY,
    MAX_DELAY,
    RETRY_LIMIT,
    BLOCKED_ABORT_STREAK,
    OUTPUT_DIR,
    DEFAULT_OP_TIMEOUT,
    NO_DISCUSSION_BLOCKED,
    NO_DISCUSSION_MISSING,
    SEARCH_OK,
    SEARCH_EMPTY,
    SEARCH_BLOCKED,
    SEARCH_ERROR,
    _IMG_HEADERS,
    _IMG_CACHE,
    _SESSION_COOKIES,
    _HARVESTED_LINKS,
    _PROXY,
    set_proxy,
    _fetch_image_bytes,
    _fetch_image,
    _preload_images,
)
from .parser import (
    escape_html,
    as_int,
    canonical_exam_code,
    normalize_exam_code,
    extract_discussion_info,
    link_matches_question,
    is_examtopics_discussion_url,
    unwrap_search_href,
    extract_matching_link,
    no_link_result,
    parse_range,
    load_all,
    has_good_data,
    upsert,
    save_progress,
)
from .crawler import (
    safe_close,
    safe_goto,
    warmup_search,
    search_engine,
    find_discussion_link,
    close_extra_tabs,
    wait_for_discussion,
    load_discussion_via_http,
    sync_browser_session,
    crawl_one_question,
)
from .exporters import (
    build_html,
    convert_to_html,
    convert_to_docx,
    _add_picture_fitted,
    _add_question_docx,
    _add_answer_key_table,
    _set_default_font,
)

__version__ = "1.1.0"
